export const portfolio = {
  owner: 'Alex',
  value: 12840,
  today: 186.2,
  todayPercent: 1.47,
  stewardship: 76,
  goal: {
    name: 'First home fund',
    current: 12840,
    target: 20000,
    horizon: 'June 2028',
  },
}

export const holdings = [
  {
    id: 'apple',
    ticker: 'AAPL',
    name: 'Pippa',
    type: 'pig',
    kind: 'Individual stock',
    value: 3284,
    weight: 25.6,
    dayChange: 2.4,
    totalReturn: 21.2,
    shares: 14.64,
    price: 224.32,
    mood: 'Curious',
    bond: 8,
    habitat: 'Orchard paddock',
    thesis: 'A durable consumer ecosystem with recurring services revenue.',
    risk: 'One company is now more than a quarter of the whole portfolio.',
    story: 'Pippa had a bright session. The important question is whether the original long-term thesis changed—not whether today was green.',
    nextStep: 'Review position size',
    position: 'pippa',
  },
  {
    id: 'nvidia',
    ticker: 'NVDA',
    name: 'Nimbus',
    type: 'horse',
    kind: 'Individual stock',
    value: 2610,
    weight: 20.3,
    dayChange: 4.8,
    totalReturn: 31.8,
    shares: 15.07,
    price: 173.19,
    mood: 'Energized',
    bond: 7,
    habitat: 'Open meadow',
    thesis: 'Demand for accelerated computing remains the central investment case.',
    risk: 'High expectations can make the position sensitive to small disappointments.',
    story: 'Nimbus is moving quickly today. Fast movement is weather, not a command. Revisit the thesis and the size of the position before doing anything.',
    nextStep: 'Check the thesis',
    position: 'nimbus',
    hasOption: true,
  },
  {
    id: 'tesla',
    ticker: 'TSLA',
    name: 'Bolt',
    type: 'cow',
    kind: 'Individual stock',
    value: 1492,
    weight: 11.6,
    dayChange: -1.2,
    totalReturn: -8.5,
    shares: 5,
    price: 298.4,
    mood: 'Resting',
    bond: 6,
    habitat: 'Creek pasture',
    thesis: 'A long-duration bet on manufacturing scale and transportation technology.',
    risk: 'The story depends on execution across several uncertain businesses.',
    story: 'Bolt is resting through a softer session. A red day is not neglect. Decide whether the evidence changed, then follow the plan you wrote in advance.',
    nextStep: 'Name the largest risk',
    position: 'bolt',
  },
  {
    id: 'vti',
    ticker: 'VTI',
    name: 'The Meadow',
    type: 'meadow',
    kind: 'Broad-market ETF',
    value: 3156,
    weight: 24.6,
    dayChange: 0.6,
    totalReturn: 9.8,
    mood: 'Steady',
    bond: 9,
    habitat: 'Wildflower commons',
    thesis: 'Broad exposure reduces dependence on any single company outcome.',
    risk: 'Diversified does not mean immune from broad market declines.',
    story: 'The Meadow moved quietly. Its job is not to win every day; it is to keep many parts of the economy working together in one habitat.',
    nextStep: 'Review diversification',
    position: 'meadow',
  },
]

export const foundations = [
  { id: 'cash', label: 'Cash reserve', value: 1298, weight: 10.1, icon: '💧', note: 'Ready for near-term needs' },
  { id: 'bonds', label: 'Bond bridge', value: 1000, weight: 7.8, icon: '🌉', note: 'A steadier counterweight' },
]

export const stories = [
  {
    id: 'weather',
    tone: 'weather',
    eyebrow: 'Market weather',
    title: 'A sunny day with fast-moving clouds',
    body: 'Your growth holdings are doing most of today’s work. That can feel good while also increasing concentration.',
    time: 'Today',
    action: 'Open the world',
    tab: 'World',
  },
  {
    id: 'apple-size',
    tone: 'risk',
    eyebrow: 'Stewardship signal',
    title: 'Pippa now fills 25.6% of the homestead',
    body: 'Nothing is automatically wrong, but one resident can increasingly determine how the whole world feels.',
    time: 'Today',
    action: 'Visit Pippa',
    holdingId: 'apple',
  },
  {
    id: 'option-school',
    tone: 'learn',
    eyebrow: 'Learning expedition',
    title: 'Nimbus found a timed options trail',
    body: 'Walk through premium, expiration, breakeven, and maximum loss using a paper-only example.',
    time: 'New',
    action: 'Explore safely',
    holdingId: 'nvidia',
    option: true,
  },
  {
    id: 'goal',
    tone: 'goal',
    eyebrow: 'Goal road',
    title: 'Your first-home fund is 64% complete',
    body: 'The destination is more important than any single day. Review whether the current risk still fits June 2028.',
    time: 'This week',
    action: 'See the plan',
    tab: 'Plan',
  },
]

export const quests = [
  {
    id: 'check-in',
    icon: '🐾',
    title: 'Check in with 3 companions',
    body: 'Notice what changed without feeling pressure to trade.',
    reward: 24,
    target: 3,
    kind: 'checkins',
  },
  {
    id: 'risk',
    icon: '🪵',
    title: 'Name Bolt’s largest risk',
    body: 'Read the risk in Bolt’s story card and mark it understood.',
    reward: 18,
    holdingId: 'tesla',
  },
  {
    id: 'option',
    icon: '🧭',
    title: 'Walk the options trail',
    body: 'Complete the risk checks for Nimbus’s paper option.',
    reward: 30,
    holdingId: 'nvidia',
    option: true,
  },
  {
    id: 'allocation',
    icon: '🌱',
    title: 'Review the habitat mix',
    body: 'Visit the Plan and inspect what is driving the portfolio.',
    reward: 16,
    tab: 'Plan',
  },
]

export const allocations = [
  { label: 'Individual stocks', value: 57.5, tone: 'stocks' },
  { label: 'Broad-market ETF', value: 24.6, tone: 'fund' },
  { label: 'Cash reserve', value: 10.1, tone: 'cash' },
  { label: 'Bonds', value: 7.8, tone: 'bond' },
]

export const optionExpedition = {
  underlying: 'NVDA',
  label: 'Sep 18, 2026 · $195 call',
  premium: 6.2,
  contractCost: 620,
  strike: 195,
  breakeven: 201.2,
  expiration: 'September 18, 2026',
  days: 49,
  contracts: 1,
  note: 'Illustrative paper contract—not a quote or recommendation.',
}

export const formatMoney = (value, digits = 0) =>
  new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: digits,
    minimumFractionDigits: digits,
  }).format(value)

export const signedPercent = value => `${value >= 0 ? '+' : '−'}${Math.abs(value).toFixed(1)}%`
export const movementClass = value => value < 0 ? 'down' : 'up'
export const getHolding = id => holdings.find(holding => holding.id === id)
